M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-06-16T22:44:42+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-16T22:44:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.350
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X93.65Y-96.25
X166.8Y-96.25
X196.65Y-96.25
X269.8Y-96.25
T2
X31.0Y-59.0
X31.0Y-135.0
X271.0Y-59.0
X271.0Y-135.0
M30
